### ISSUE TITLE
Místo echo. je echo .

### ISSUE THREAD

**Issue by NotVibeCodedSlop** [Grizlikk/GrizlikYT#1]
https://github.com/Grizlikk/GrizlikYT/blob/45a621c7e4aad6eef587818a9243d90007861ce0/Videa/Jak%20funguje%20trojsk%C3%BD%20k%C5%AF%C5%88/Hra%20clean%20verze.bat#L36

**Comment by Grizlikk** [comment]
Díky za upozornění, všimnul jsem si toho už dříve, ale nechal jsem to tak, protože když se podíváš na ten program přímo v tom videu, tak tam je taky "echo ." místo "echo." ;)
