### ISSUE TITLE
Heslo som zistil bez použitia hry :)

### ISSUE THREAD

**Issue by sleduj-tv** [Grizlikk/GrizlikYT#2]
Ľudia fakt ste takí tupí, že nedáte upraviť a potom si to dole na konci nájdete ten link na to video a Discord? A tí, čo majú Linux teraz plaču

**Comment by Grizlikk** [comment]
Doslova jsem ani neplánoval, že by si ten soubor někdo spouštěl, právě kvůli tomu, že by to fungovalo jenom pro Windows
Na tom je aspoň vidět, kolik lidí napadne, že vlastně znají zdrojový kód toho souboru :D

**Comment by sleduj-tv** [comment]
Zvláštne, potom som ju zahral...
