### ISSUE TITLE
zmazať diakritiku 

### ISSUE THREAD

**Issue by xhyrom** [Grizlikk/GrizlikYT#3]
Vážne, v menách priečinkov diakritika? Prosím opraviť!! 😅😁 

A nahradiť medzery s `-` alebo `_`

**Comment by Grizlikk** [comment]
Zrovna tady mi přijde, že to až tolik nevadí, protože tohle je spíše takové úložiště dat, než nějaký projekt :D 
Spíš mě přijdou trochu zvláštní ty emotikony v názvech některých složek, protože já mám kopii všech složek i u sebe na PC, ale ty tam jsou zase proto, aby se ty složky jmenovaly stejně, jako videa, ze kterých ty soubory pochází 😁
Ale teď mě napadá, že bych mohl ke všem videím dát přímé odkazy na tu konkrétní složku, protože už to začíná být lehce nepřehledné
